import GeoSBT

#print axioms graph_edist_triangle
#print axioms GeoSBT.Protocol.cost_append
#print axioms GeoSBT.Protocol.cost_reverse
#print axioms GeoSBT.weightedEdist_self
#print axioms GeoSBT.weightedEdist_triangle
#print axioms GeoSBT.weightedEdist_symm
#print axioms GeoSBT.weightedPseudoEMetricSpace
#print axioms separation_quotient_metric
#print axioms separation_quotient_dist_eq_zero
#print axioms separation_quotient_emetric
#print axioms separation_quotient_edist_mk
#print axioms separation_quotient_edist_eq_zero
#print axioms GeoSBT.weightedSeparationMetric
#print axioms GeoSBT.weightedSeparation_edist_mk
#print axioms GeoSBT.flooredLikelihoodCost_nonneg
#print axioms GeoSBT.flooredLikelihoodCost_encoding
#print axioms pythagoras_real

#print axioms GeoSBT.stochastic_mul
#print axioms GeoSBT.coarseMatrix_stochastic
#print axioms GeoSBT.stochastic_power
#print axioms GeoSBT.closure_and_macro_stochastic
#print axioms GeoSBT.closure_defect_factorization
#print axioms GeoSBT.lift_coarse_identity
#print axioms GeoSBT.totalVariation_push_row_bound
#print axioms GeoSBT.totalVariation_extreme_point_iff
#print axioms GeoSBT.push_distribution
#print axioms GeoSBT.push_push
#print axioms GeoSBT.totalVariation_triangle
#print axioms GeoSBT.closure_repetition_bound
#print axioms GeoSBT.disjoint_push_l1
#print axioms GeoSBT.fiber_push_l1_isometry
#print axioms GeoSBT.totalVariation_fiber_lift
#print axioms GeoSBT.totalVariation_point_eq_escape
#print axioms GeoSBT.prototype_stability_eq_escape
#print axioms GeoSBT.closure_defect_le_macro_escape
#print axioms GeoSBT.hilbert_quadrilateral
#print axioms GeoSBT.no_hilbert_uniform_approximation
#print axioms GeoSBT.gasket_quadrilateral_gap
#print axioms GeoSBT.gasket_limit_quadrilateral_gap
#print axioms GeoSBT.gasket_log_bracket
#print axioms GeoSBT.gasket_staged_log_bracket
#print axioms GeoSBT.squared_readout_error_le
#print axioms GeoSBT.quadratic_cost_readout_error
#print axioms GeoSBT.abs_log_le_relative_error
#print axioms GeoSBT.log_cost_error
#print axioms GeoSBT.centered_log_ratio_error
#print axioms GeoSBT.cost_axis_residual_bound
#print axioms GeoSBT.covariantShift_commute_iff
#print axioms GeoSBT.covariantShift_gauge
#print axioms GeoSBT.plaquetteHolonomy_gauge
#print axioms GeoSBT.triangleHolonomy_eq_one_iff
#print axioms GeoSBT.macro_return_le_fiber_bound
#print axioms GeoSBT.prototype_defect_ge_fiber_escape
#print axioms GeoSBT.triangleHolonomy_common_chart
#print axioms GeoSBT.triangle_transport_error
#print axioms GeoSBT.normalized_angle_error
#print axioms GeoSBT.Protocol.reference_le_cost
#print axioms GeoSBT.weightedEdist_reference_bracket
#print axioms GeoSBT.likelihood_cost_exp_bracket
